- id: nbqa
  name: nbqa
  description: "Run any standard Python code quality tool on a Jupyter Notebook"
  entry: nbqa
  language: python
  language_version: python3
  require_serial: true
  types: [jupyter]
