- id: nbqa
  name: nbqa
  description: Run any standard Python code quality tool on a Jupyter Notebook
  entry: nbqa
  language: python
  require_serial: true
  types_or: [jupyter, markdown]
- id: nbqa-black
  name: nbqa-black
  description: Run 'black' on a Jupyter Notebook
  entry: nbqa black
  language: python
  require_serial: true
  types_or: [jupyter, markdown]
  additional_dependencies: [black]
- id: nbqa-check-ast
  name: nbqa-check-ast
  description: Run 'check-ast' on a Jupyter Notebook
  entry: nbqa pre_commit_hooks.check_ast
  language: python
  require_serial: true
  types_or: [jupyter, markdown]
  additional_dependencies: [pre-commit-hooks]
  args: [--nbqa-dont-skip-bad-cells]
- id: nbqa-flake8
  name: nbqa-flake8
  description: Run 'flake8' on a Jupyter Notebook
  entry: nbqa flake8
  language: python
  require_serial: true
  types_or: [jupyter, markdown]
  additional_dependencies: [flake8]
- id: nbqa-isort
  name: nbqa-isort
  description: Run 'isort' on a Jupyter Notebook
  entry: nbqa isort
  language: python
  require_serial: true
  types_or: [jupyter, markdown]
  additional_dependencies: [isort]
- id: nbqa-mypy
  name: nbqa-mypy
  description: Run 'mypy' on a Jupyter Notebook
  entry: nbqa mypy
  language: python
  require_serial: true
  types_or: [jupyter, markdown]
  additional_dependencies: [mypy]
- id: nbqa-pylint
  name: nbqa-pylint
  description: Run 'pylint' on a Jupyter Notebook
  entry: nbqa pylint
  language: python
  require_serial: true
  types_or: [jupyter, markdown]
  additional_dependencies: [pylint]
- id: nbqa-pyupgrade
  name: nbqa-pyupgrade
  description: Run 'pyupgrade' on a Jupyter Notebook
  entry: nbqa pyupgrade
  language: python
  require_serial: true
  types_or: [jupyter, markdown]
  additional_dependencies: [pyupgrade]
- id: nbqa-yapf
  name: nbqa-yapf
  description: Run 'yapf' on a Jupyter Notebook
  entry: nbqa yapf --in-place
  language: python
  require_serial: true
  types_or: [jupyter, markdown]
  additional_dependencies: [yapf]
- id: nbqa-autopep8
  name: nbqa-autopep8
  description: Run 'autopep8' on a Jupyter Notebook
  entry: nbqa autopep8 -i
  language: python
  require_serial: true
  types_or: [jupyter, markdown]
  additional_dependencies: [autopep8]
- id: nbqa-pydocstyle
  name: nbqa-pydocstyle
  description: Run 'pydocstyle' on a Jupyter Notebook
  entry: nbqa pydocstyle
  language: python
  require_serial: true
  types_or: [jupyter, markdown]
  additional_dependencies: [pydocstyle]
- id: nbqa-ruff
  name: nbqa-ruff
  description: Run 'ruff' on a Jupyter Notebook
  entry: nbqa ruff
  language: python
  additional_dependencies: [ruff]
  require_serial: true
  types_or: [jupyter, markdown]

