[mypy]
disallow_untyped_defs = True

# 3rd party libraries
[mypy-pytest]
ignore_missing_imports = True
[mypy-_pytest.capture]
ignore_missing_imports = True
[mypy-setuptools]
ignore_missing_imports = True

# non-nbqa files
[mypy-setup]
ignore_errors = True
