name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            /opt/hostedtoolcache/Python/
            ~\AppData\Local\pip\Cache
            c:\hostedtoolcache\windows\python\
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      # This is required since pylint is used in pre-commit as a local hook
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - uses: pre-commit/action@v2.0.0
