# I need a separate job for this as PyLint requires an old version of isort.

name: pylint

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: install-pylint
      run: python -m pip install --upgrade pip pylint
    - name: run-pylint
      run: pylint nbqa tests
